using Slypn.Api.Models;

namespace Slypn.Api.Services;

public sealed class MockDataService : IMockDataService
{
    public IReadOnlyList<Article> Articles { get; } = new[]
    {
        new Article(
            "a1", "working-with-parkinsons",
            "Living well at work with Parkinson's",
            "Practical thinking on workplace adjustments, when to disclose, and how to keep doing the job you love after a Parkinson's diagnosis.",
            "A Parkinson's diagnosis at working age often comes with a stack of practical questions about the job.\n\nStart by reading the rights you already have. In the UK, Parkinson's is covered by the Equality Act 2010, meaning employers must make reasonable adjustments.\n\nWhen to disclose is personal. Many SLYPN members tell us they wished they'd waited - and just as many wish they'd told their manager sooner.\n\nFinally, the small daily things compound. Lay out clothes the night before. Tackle the hardest task in your best-medication window.",
            "Helen Stoinanov",
            new DateTime(2026, 5, 12, 9, 0, 0, DateTimeKind.Utc),
            6, "Living with Parkinson's",
            new[] { "work", "rights", "adjustments" }),
        new Article(
            "a2", "medication-side-effects",
            "Understanding the medication side effects no one warned you about",
            "A frank look at the common (and less common) side effects of the medications most often prescribed for Parkinson's - and what to do when they show up.",
            "Levodopa is still the most effective treatment for Parkinson's, but the body's relationship with it is messy.\n\nDopamine agonists carry their own profile. Impulse-control issues are well documented but under-discussed.\n\nThis article is not medical advice - talk to your specialist nurse - but it's the conversation we wish we'd had earlier.",
            "Kate Wellington",
            new DateTime(2026, 4, 28, 9, 0, 0, DateTimeKind.Utc),
            8, "Treatment",
            new[] { "medication", "side-effects", "levodopa" }),
        new Article(
            "a3", "support-network-at-any-age",
            "Building a support network at any age",
            "Why peer support matters more than people expect, and how SLYPN works to provide it for the South London under-50s.",
            "We started SLYPN in 2011 because the support that existed at the time wasn't built around working-age people.\n\nFifteen years on, the format has barely changed: coffee meet-ups across South London, occasional drinks, a few activities a year.",
            "Sarah Webb",
            new DateTime(2026, 4, 10, 9, 0, 0, DateTimeKind.Utc),
            5, "Community",
            new[] { "peer-support", "history", "founders" }),
        new Article(
            "a4", "sleep-exercise-parkinsons",
            "Sleep, exercise, and Parkinson's - what the evidence actually says",
            "Cutting through the noise on lifestyle interventions: what helps, what doesn't, and what to try first.",
            "There is no shortage of advice online about lifestyle changes for Parkinson's. Some of it is genuinely useful. Some of it is wishful thinking.\n\nExercise - particularly aerobic and resistance training - has the strongest evidence for slowing symptom progression.",
            "Helen Stoinanov",
            new DateTime(2026, 3, 22, 9, 0, 0, DateTimeKind.Utc),
            7, "Lifestyle",
            new[] { "sleep", "exercise", "evidence" }),
        new Article(
            "a5", "what-to-bring-to-your-first-meetup",
            "What to bring (and expect) at your first SLYPN meet-up",
            "A short, practical note for anyone thinking about coming to a meet-up for the first time.",
            "Just yourself. That's the honest answer.\n\nWe meet in coffee shops or pubs around South London, usually for a couple of hours in the evening.",
            "Kate Wellington",
            new DateTime(2026, 3, 4, 9, 0, 0, DateTimeKind.Utc),
            3, "Community",
            new[] { "newcomers", "meet-ups" }),
    };

    public IReadOnlyList<BlogPost> BlogPosts { get; } = new[]
    {
        new BlogPost("b1", "brixton-meetup-may-2026",
            "Brixton coffee meet-up - May recap",
            "Eleven of us, two new faces, far too much cake. A short recap from Tuesday night.",
            "We had eleven members at Federation Coffee in Brixton on Tuesday - two new, both newly diagnosed.",
            "Sarah Webb",
            new DateTime(2026, 5, 15, 20, 30, 0, DateTimeKind.Utc)),
        new BlogPost("b2", "welcome-new-members-q2",
            "Welcome to our new members",
            "A short hello to the eight people who have joined the network since the start of April.",
            "We've had a busy spring. Eight new people have joined SLYPN since the start of April.",
            "Helen Stoinanov",
            new DateTime(2026, 5, 2, 9, 0, 0, DateTimeKind.Utc)),
        new BlogPost("b3", "thank-you-5k-runners",
            "Thank you to our 5k runners",
            "Our spring fundraiser raised £4,820 for Parkinson's UK. Thank you to everyone who ran, walked, or cheered.",
            "Forty of us turned out in Hyde Park on a damp Sunday morning. Between sponsorship and matched donations we raised £4,820.",
            "Kate Wellington",
            new DateTime(2026, 4, 21, 9, 0, 0, DateTimeKind.Utc)),
    };

    public IReadOnlyList<CommunityEvent> Events { get; } = new[]
    {
        new CommunityEvent("e1", "Coffee meet-up - Clapham", "Coffee meet-up",
            new DateTimeOffset(2026, 5, 28, 18, 30, 0, TimeSpan.FromHours(1)),
            new DateTimeOffset(2026, 5, 28, 20, 30, 0, TimeSpan.FromHours(1)),
            "WatchHouse, Clapham Common SW4",
            "Our regular monthly meet-up. Drop in any time between 6:30 and 8:30.",
            null),
        new CommunityEvent("e2", "Q&A with a movement-disorder neurologist", "Q&A",
            new DateTimeOffset(2026, 6, 4, 19, 0, 0, TimeSpan.FromHours(1)),
            new DateTimeOffset(2026, 6, 4, 20, 30, 0, TimeSpan.FromHours(1)),
            "Online (Zoom)",
            "An hour-and-a-half with Dr Priya Iyer (King's College Hospital).",
            "https://example.com/slypn/qa-june"),
        new CommunityEvent("e3", "Summer drinks - Greenwich", "Drinks",
            new DateTimeOffset(2026, 6, 13, 19, 0, 0, TimeSpan.FromHours(1)),
            new DateTimeOffset(2026, 6, 13, 22, 0, 0, TimeSpan.FromHours(1)),
            "The Trafalgar Tavern, Greenwich SE10",
            "Our summer social. Partners and carers welcome.",
            null),
        new CommunityEvent("e4", "Carer-only catch-up", "Carer session",
            new DateTimeOffset(2026, 6, 18, 19, 30, 0, TimeSpan.FromHours(1)),
            new DateTimeOffset(2026, 6, 18, 21, 0, 0, TimeSpan.FromHours(1)),
            "Online (Zoom)",
            "A small group for partners and carers of SLYPN members.",
            null),
        new CommunityEvent("e5", "Coffee meet-up - Dulwich", "Coffee meet-up",
            new DateTimeOffset(2026, 6, 25, 18, 30, 0, TimeSpan.FromHours(1)),
            new DateTimeOffset(2026, 6, 25, 20, 30, 0, TimeSpan.FromHours(1)),
            "Romeo Jones, Dulwich Village SE21",
            "June meet-up. Same format as Clapham.",
            null),
        new CommunityEvent("e6", "Beat Parkinson's 5k - autumn", "Fundraising",
            new DateTimeOffset(2026, 9, 20, 9, 30, 0, TimeSpan.FromHours(1)),
            new DateTimeOffset(2026, 9, 20, 12, 0, 0, TimeSpan.FromHours(1)),
            "Hyde Park, London W2",
            "Our autumn fundraiser for Parkinson's UK.",
            "https://example.com/slypn/5k-autumn"),
        new CommunityEvent("e7", "Coffee meet-up - Tooting", "Coffee meet-up",
            new DateTimeOffset(2026, 7, 23, 18, 30, 0, TimeSpan.FromHours(1)),
            new DateTimeOffset(2026, 7, 23, 20, 30, 0, TimeSpan.FromHours(1)),
            "Brick House, Tooting SW17",
            "July meet-up.",
            null),
    };

    public IReadOnlyList<Resource> Resources { get; } = new[]
    {
        new Resource("r1", "Parkinson's UK helpline",
            "Free, confidential support from trained advisers. Mon-Fri 9am-7pm, Sat 10am-2pm.",
            "https://www.parkinsons.org.uk/information-and-support/helpline-and-local-advisers",
            "Parkinson's UK"),
        new Resource("r2", "Parkinson's UK - for the newly diagnosed",
            "The single best starting point if you've been diagnosed in the last few months.",
            "https://www.parkinsons.org.uk/information-and-support/newly-diagnosed",
            "Parkinson's UK"),
        new Resource("r3", "NHS - Parkinson's disease overview",
            "Plain-English summary of symptoms, treatment, and what to expect from NHS care.",
            "https://www.nhs.uk/conditions/parkinsons-disease/",
            "NHS"),
        new Resource("r4", "King's College Hospital movement disorders clinic",
            "The specialist movement-disorders unit at King's College Hospital, Denmark Hill.",
            "https://www.kch.nhs.uk/services/neurology",
            "Local"),
        new Resource("r5", "Deep brain stimulation (DBS) - Parkinson's UK",
            "What DBS is, who it might suit, and how to be referred for an assessment.",
            "https://www.parkinsons.org.uk/information-and-support/deep-brain-stimulation",
            "Parkinson's UK"),
        new Resource("r6", "Personal Independence Payment (PIP)",
            "The main UK benefit you may be entitled to as a working-age adult with Parkinson's.",
            "https://www.gov.uk/pip",
            "Benefits"),
        new Resource("r7", "Access to Work - disability employment support",
            "A government grant scheme to pay for workplace adjustments your employer cannot reasonably cover.",
            "https://www.gov.uk/access-to-work",
            "Benefits"),
        new Resource("r8", "Carers UK",
            "Advice, peer support, and a helpline specifically for unpaid carers.",
            "https://www.carersuk.org/",
            "Carers"),
        new Resource("r9", "Parkinson's UK - current research",
            "The charity's research overview, including ways to take part in clinical studies.",
            "https://www.parkinsons.org.uk/research",
            "Research"),
    };

    public IReadOnlyList<Newsletter> Newsletters { get; } = new[]
    {
        new Newsletter("n1", "May 2026", new DateOnly(2026, 5, 1),
            "Spring fundraiser write-up, eight new members welcomed, and a heads-up about the autumn 5k.",
            new[] { "Spring fundraiser", "New members", "Autumn 5k", "Q&A with neurologist" }),
        new Newsletter("n2", "April 2026", new DateOnly(2026, 4, 1),
            "A short feature on medication windows, the spring meet-up schedule, and an introduction from a new member volunteer.",
            new[] { "Medication windows", "Meet-up schedule", "Member feature" }),
        new Newsletter("n3", "March 2026", new DateOnly(2026, 3, 1),
            "Sleep, exercise, and Parkinson's - a long-form piece - plus the dates for the spring fundraiser.",
            new[] { "Sleep and exercise", "Fundraiser dates", "Carer session announcement" }),
        new Newsletter("n4", "February 2026", new DateOnly(2026, 2, 1),
            "A new year retrospective from the founders, plus thoughts on disclosure at work from members.",
            new[] { "Founders retrospective", "Work and disclosure" }),
    };
}
